### Import Libraries

In [1]:
import pandas as pd
import re
import os

### Create Folder and Load Raw Data

In [3]:
os.makedirs("../data/processed", exist_ok=True)
df = pd.read_csv("data/raw/ai_tweets_raw.csv")
df.head()

,user,text,date
0,karpathy,AI will become the new electricity. Exciting t...,2024-01-12
1,karpathy,Training models requires patience and compute ...,2024-03-05
2,karpathy,Neural networks are evolving faster than expec...,2024-04-10
3,geoffreyhinton,Deep learning surprised everyone. And it will ...,2024-02-01
4,geoffreyhinton,We must use AI responsibly for humanity.,2024-05-15

### Define Cleaning Function

In [4]:
def clean_text(text):
    text = re.sub(r"http\S+", "", text) 
    text = re.sub(r"[@#]\S+", "", text)
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)
    text = text.lower().strip()
    return text


### Apply Cleaning and Save Processed Data

In [5]:
df["clean_text"] = df["text"].apply(clean_text)
df.to_parquet("../data/processed/cleaned_tweets.parquet", index=False)
df.head()

,user,text,date,clean_text
0,karpathy,AI will become the new electricity. Exciting t...,2024-01-12,ai will become the new electricity exciting ti...
1,karpathy,Training models requires patience and compute ...,2024-03-05,training models requires patience and compute ...
2,karpathy,Neural networks are evolving faster than expec...,2024-04-10,neural networks are evolving faster than expected
3,geoffreyhinton,Deep learning surprised everyone. And it will ...,2024-02-01,deep learning surprised everyone and it will a...
4,geoffreyhinton,We must use AI responsibly for humanity.,2024-05-15,we must use ai responsibly for humanity